[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 12;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = internal_64MHz;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 23;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = second_pll/CLKOP;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 1;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = int_clk_out;
GLOBAL_PRIMARY_2_DRIVERTYPE = OSC;
GLOBAL_PRIMARY_2_LOADNUM = 195;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = sdr_rxclk_c;
GLOBAL_PRIMARY_3_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_3_LOADNUM = 135;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = internal_80MHz;
GLOBAL_PRIMARY_4_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_4_LOADNUM = 108;
; Global primary clock #5
GLOBAL_PRIMARY_5_SIGNALNAME = stm_fpga_spare5_c;
GLOBAL_PRIMARY_5_DRIVERTYPE = PIO;
GLOBAL_PRIMARY_5_LOADNUM = 0;
; Global primary clock #6
GLOBAL_PRIMARY_6_SIGNALNAME = main_reset_n_N_208;
GLOBAL_PRIMARY_6_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_6_LOADNUM = 0;
; Global primary clock #7
GLOBAL_PRIMARY_7_SIGNALNAME = lvds_rx_09_inst/sdr_rxclk_c_enable_40;
GLOBAL_PRIMARY_7_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_7_LOADNUM = 0;
; Global primary clock #8
GLOBAL_PRIMARY_8_SIGNALNAME = lvds_rx_24_inst/sdr_rxclk_c_enable_73;
GLOBAL_PRIMARY_8_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_8_LOADNUM = 0;
; Global primary clock #9
GLOBAL_PRIMARY_9_SIGNALNAME = fpga_led_N_383;
GLOBAL_PRIMARY_9_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_9_LOADNUM = 0;
; Global primary clock #10
GLOBAL_PRIMARY_10_SIGNALNAME = dpll_clkout2_c;
GLOBAL_PRIMARY_10_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_10_LOADNUM = 1;
; Global primary clock #11
GLOBAL_PRIMARY_11_SIGNALNAME = dpll_clkout0_c;
GLOBAL_PRIMARY_11_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_11_LOADNUM = 1;
; I/O Bank 0 Usage
BANK_0_USED = 15;
BANK_0_AVAIL = 24;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 8;
BANK_1_AVAIL = 32;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 8;
BANK_2_AVAIL = 32;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 4;
BANK_3_AVAIL = 32;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
; I/O Bank 6 Usage
BANK_6_USED = 4;
BANK_6_AVAIL = 32;
BANK_6_VCCIO = 2.5V;
BANK_6_VREF1 = NA;
BANK_6_VREF2 = NA;
; I/O Bank 7 Usage
BANK_7_USED = 6;
BANK_7_AVAIL = 32;
BANK_7_VCCIO = 2.5V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
; I/O Bank 8 Usage
BANK_8_USED = 0;
BANK_8_AVAIL = 13;
BANK_8_VCCIO = 3.3V;
BANK_8_VREF1 = NA;
BANK_8_VREF2 = NA;
