/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n fifo_dc_32in_1out -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type ebfifo -depth 4 -width 32 -rwidth 1 -reset_rel SYNC -pe -1 -pf -1 -fdc C:/Users/julianstj/Desktop/WorkNotes/Projects/PTP/WiWi/SDR/Software/ECP5_Test/fifo_dc_32in_1out/fifo_dc_32in_1out.fdc  */
/* Fri Dec 06 12:57:21 2024 */


`timescale 1 ns / 1 ps
module fifo_dc_32in_1out (Data, WrClock, RdClock, WrEn, RdEn, Reset, 
    RPReset, Q, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [0:0] Q;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire rcount_w3;
    wire rcount_w2;
    wire rcount_w1;
    wire rcount_w0;
    wire r_g2b_xor_cluster_1;
    wire r_g2b_xor_cluster_0;
    wire w_gdata_0;
    wire w_gdata_1;
    wire wptr_0;
    wire wptr_1;
    wire wptr_2;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire rptr_0;
    wire rptr_1;
    wire rptr_2;
    wire rptr_3;
    wire rptr_4;
    wire rptr_5;
    wire rptr_6;
    wire rptr_7;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire co1;
    wire co0;
    wire wcount_2;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co3;
    wire co2;
    wire rcount_7;
    wire rden_i;
    wire cmp_ci;
    wire rcount_0;
    wire rcount_1;
    wire co0_2;
    wire rcount_2;
    wire rcount_3;
    wire co1_2;
    wire wcount_r0;
    wire rcount_4;
    wire rcount_5;
    wire co2_1;
    wire wcount_r1;
    wire empty_cmp_clr;
    wire rcount_6;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire wren_i;
    wire cmp_ci_1;
    wire rcount_w5;
    wire rcount_w6;
    wire wcount_0;
    wire wcount_1;
    wire co0_3;
    wire full_cmp_clr;
    wire full_cmp_set;
    wire full_d;
    wire scuba_vhi;
    wire scuba_vlo;
    wire full_d_c;

    AND2 AND2_t11 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t10 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t9 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t8 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t7 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t6 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t5 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t4 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t3 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t2 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t1 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t0 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(w_gcount_r21), .AD2(w_gcount_r22), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r1));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(w_gcount_r22), 
        .AD0(scuba_vlo), .DO0(wcount_r0));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(r_gcount_w26), 
        .AD0(r_gcount_w27), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(r_gcount_w22), 
        .AD0(r_gcount_w23), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w6));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(r_gcount_w27), 
        .AD0(scuba_vlo), .DO0(rcount_w5));

    defparam LUT4_7.initval =  16'h6996 ;
    ROM16X1A LUT4_7 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(rcount_w6), .DO0(rcount_w3));

    defparam LUT4_6.initval =  16'h6996 ;
    ROM16X1A LUT4_6 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(rcount_w5), .DO0(rcount_w2));

    defparam LUT4_5.initval =  16'h6996 ;
    ROM16X1A LUT4_5 (.AD3(r_gcount_w21), .AD2(r_gcount_w22), .AD1(r_gcount_w23), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w1));

    defparam LUT4_4.initval =  16'h6996 ;
    ROM16X1A LUT4_4 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w0));

    defparam LUT4_3.initval =  16'h0410 ;
    ROM16X1A LUT4_3 (.AD3(rptr_7), .AD2(rcount_7), .AD1(w_gcount_r22), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set));

    defparam LUT4_2.initval =  16'h1004 ;
    ROM16X1A LUT4_2 (.AD3(rptr_7), .AD2(rcount_7), .AD1(w_gcount_r22), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr));

    defparam LUT4_1.initval =  16'h0140 ;
    ROM16X1A LUT4_1 (.AD3(wptr_2), .AD2(wcount_2), .AD1(r_gcount_w27), .AD0(scuba_vlo), 
        .DO0(full_cmp_set));

    defparam LUT4_0.initval =  16'h4001 ;
    ROM16X1A LUT4_0 (.AD3(wptr_2), .AD2(wcount_2), .AD1(r_gcount_w27), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr));

    defparam pdp_ram_0_0_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_0.CSDECODE_R = "0b000" ;
    defparam pdp_ram_0_0_0.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_0_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_0.REGMODE = "NOREG" ;
    defparam pdp_ram_0_0_0.DATA_WIDTH_R = 1 ;
    defparam pdp_ram_0_0_0.DATA_WIDTH_W = 36 ;
    PDPW16KD pdp_ram_0_0_0 (.DI35(scuba_vlo), .DI34(Data[31]), .DI33(Data[30]), 
        .DI32(Data[29]), .DI31(Data[28]), .DI30(Data[27]), .DI29(Data[26]), 
        .DI28(Data[25]), .DI27(Data[24]), .DI26(scuba_vlo), .DI25(Data[23]), 
        .DI24(Data[22]), .DI23(Data[21]), .DI22(Data[20]), .DI21(Data[19]), 
        .DI20(Data[18]), .DI19(Data[17]), .DI18(Data[16]), .DI17(scuba_vlo), 
        .DI16(Data[15]), .DI15(Data[14]), .DI14(Data[13]), .DI13(Data[12]), 
        .DI12(Data[11]), .DI11(Data[10]), .DI10(Data[9]), .DI9(Data[8]), 
        .DI8(scuba_vlo), .DI7(Data[7]), .DI6(Data[6]), .DI5(Data[5]), .DI4(Data[4]), 
        .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), .DI0(Data[0]), .ADW8(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW6(scuba_vlo), .ADW5(scuba_vlo), .ADW4(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW2(scuba_vlo), .ADW1(wptr_1), .ADW0(wptr_0), 
        .BE3(scuba_vhi), .BE2(scuba_vhi), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(wren_i), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(scuba_vhi), .ADR13(scuba_vlo), .ADR12(scuba_vlo), .ADR11(scuba_vlo), 
        .ADR10(scuba_vlo), .ADR9(scuba_vlo), .ADR8(scuba_vlo), .ADR7(scuba_vlo), 
        .ADR6(rptr_6), .ADR5(rptr_5), .ADR4(rptr_4), .ADR3(rptr_3), .ADR2(rptr_2), 
        .ADR1(rptr_1), .ADR0(rptr_0), .CER(rden_i), .OCER(rden_i), .CLKR(RdClock), 
        .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), .RST(Reset), 
        .DO35(), .DO34(), .DO33(), .DO32(), .DO31(), .DO30(), .DO29(), .DO28(), 
        .DO27(), .DO26(), .DO25(), .DO24(), .DO23(), .DO22(), .DO21(), .DO20(), 
        .DO19(), .DO18(), .DO17(), .DO16(), .DO15(), .DO14(), .DO13(), .DO12(), 
        .DO11(), .DO10(), .DO9(), .DO8(), .DO7(), .DO6(), .DO5(), .DO4(), 
        .DO3(), .DO2(), .DO1(), .DO0(Q[0]))
             /* synthesis MEM_LPC_FILE="fifo_dc_32in_1out.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3BX FF_56 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_47 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_23 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_21 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_20 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_19 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_18 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_17 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_16 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_15 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_14 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_13 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_12 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_11 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_10 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_9 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_8 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_7 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_6 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_5 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_4 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_3 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_2 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_1 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    defparam w_gctr_cia.INJECT1_1 = "NO" ;
    defparam w_gctr_cia.INJECT1_0 = "NO" ;
    defparam w_gctr_cia.INIT1 =  16'h66AA ;
    defparam w_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_gctr_ci));

    defparam w_gctr_0.INJECT1_1 = "NO" ;
    defparam w_gctr_0.INJECT1_0 = "NO" ;
    defparam w_gctr_0.INIT1 =  16'h66AA ;
    defparam w_gctr_0.INIT0 =  16'h66AA ;
    CCU2C w_gctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_gctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0));

    defparam w_gctr_1.INJECT1_1 = "NO" ;
    defparam w_gctr_1.INJECT1_0 = "NO" ;
    defparam w_gctr_1.INIT1 =  16'h66AA ;
    defparam w_gctr_1.INIT0 =  16'h66AA ;
    CCU2C w_gctr_1 (.A0(wcount_2), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(iwcount_2), .S1(), .COUT(co1));

    defparam r_gctr_cia.INJECT1_1 = "NO" ;
    defparam r_gctr_cia.INJECT1_0 = "NO" ;
    defparam r_gctr_cia.INIT1 =  16'h66AA ;
    defparam r_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_gctr_ci));

    defparam r_gctr_0.INJECT1_1 = "NO" ;
    defparam r_gctr_0.INJECT1_0 = "NO" ;
    defparam r_gctr_0.INIT1 =  16'h66AA ;
    defparam r_gctr_0.INIT0 =  16'h66AA ;
    CCU2C r_gctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_gctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_1));

    defparam r_gctr_1.INJECT1_1 = "NO" ;
    defparam r_gctr_1.INJECT1_0 = "NO" ;
    defparam r_gctr_1.INIT1 =  16'h66AA ;
    defparam r_gctr_1.INIT0 =  16'h66AA ;
    CCU2C r_gctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(ircount_2), .S1(ircount_3), .COUT(co1_1));

    defparam r_gctr_2.INJECT1_1 = "NO" ;
    defparam r_gctr_2.INJECT1_0 = "NO" ;
    defparam r_gctr_2.INIT1 =  16'h66AA ;
    defparam r_gctr_2.INIT0 =  16'h66AA ;
    CCU2C r_gctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(ircount_4), .S1(ircount_5), .COUT(co2));

    defparam r_gctr_3.INJECT1_1 = "NO" ;
    defparam r_gctr_3.INJECT1_0 = "NO" ;
    defparam r_gctr_3.INIT1 =  16'h66AA ;
    defparam r_gctr_3.INIT0 =  16'h66AA ;
    CCU2C r_gctr_3 (.A0(rcount_6), .A1(rcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(ircount_6), .S1(ircount_7), .COUT(co3));

    defparam empty_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam empty_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam empty_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam empty_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam empty_cmp_0.INJECT1_1 = "NO" ;
    defparam empty_cmp_0.INJECT1_0 = "NO" ;
    defparam empty_cmp_0.INIT1 =  16'h99AA ;
    defparam empty_cmp_0.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_2));

    defparam empty_cmp_1.INJECT1_1 = "NO" ;
    defparam empty_cmp_1.INJECT1_0 = "NO" ;
    defparam empty_cmp_1.INIT1 =  16'h99AA ;
    defparam empty_cmp_1.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(co1_2));

    defparam empty_cmp_2.INJECT1_1 = "NO" ;
    defparam empty_cmp_2.INJECT1_0 = "NO" ;
    defparam empty_cmp_2.INIT1 =  16'h99AA ;
    defparam empty_cmp_2.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(wcount_r0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(), .S1(), .COUT(co2_1));

    defparam empty_cmp_3.INJECT1_1 = "NO" ;
    defparam empty_cmp_3.INJECT1_0 = "NO" ;
    defparam empty_cmp_3.INIT1 =  16'h99AA ;
    defparam empty_cmp_3.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_3 (.A0(rcount_6), .A1(empty_cmp_set), .B0(wcount_r1), 
        .B1(empty_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_1), .S0(), .S1(), .COUT(empty_d_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(empty_d_c), .S0(empty_d), .S1(), .COUT());

    defparam full_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam full_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam full_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam full_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam full_cmp_0.INJECT1_1 = "NO" ;
    defparam full_cmp_0.INJECT1_0 = "NO" ;
    defparam full_cmp_0.INIT1 =  16'h99AA ;
    defparam full_cmp_0.INIT0 =  16'h99AA ;
    CCU2C full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w5), .B1(rcount_w6), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_3));

    defparam full_cmp_1.INJECT1_1 = "NO" ;
    defparam full_cmp_1.INJECT1_0 = "NO" ;
    defparam full_cmp_1.INIT1 =  16'h99AA ;
    defparam full_cmp_1.INIT0 =  16'h99AA ;
    CCU2C full_cmp_1 (.A0(full_cmp_set), .A1(scuba_vlo), .B0(full_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_3), .S0(), .S1(), .COUT(full_d_c));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(full_d_c), .S0(full_d), .S1(), .COUT());

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_0 MEM_LPC_FILE fifo_dc_32in_1out.lpc
    // exemplar attribute pdp_ram_0_0_0 MEM_INIT_FILE 
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
