/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Dec 08 09:47:04 2024 */

/* parameterized module instance */
internal_pll __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), 
    .CLKOS3( ), .LOCK( ));
