/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Dec 08 09:09:50 2024 */

/* parameterized module instance */
pll_10MHzInput __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
